# Generated by Django 6.0.4 on 2026-06-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agency_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
