# Generated by Django 6.0.4 on 2026-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_bathrooms_property_bedrooms_property_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
