# Generated by Django 6.0.3 on 2026-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
